### ISSUE TITLE
neat module !

### ISSUE THREAD

**Issue by davephillips** [SpektroAudio/Seasons#1]
Just a quick note to let you know I've successfully built your plugin on Fedora 23 Linux and loaded it into the latest VCV Rack v1.dev version. Thank you for this gift, it is a very cool module. I've been having lots of fun patching it into Prism, Elements, EV3, and other destinations, hopefully I'll post a video soon.

Best regards,

Dave Phillips

**Comment by icaroferre** [comment]
Ah, thanks for the feedback @davephillips! Glad you're enjoying it!
Please let me know (or tag @SpektroAudio) if you share any videos using it!

Best,
